# Generated by Django 4.0.4 on 2022-04-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='images',
            new_name='image',
        ),
    ]
